version: '3.8'

services:
  web:
    image: web-image
    build: ./frontend
    ports:
      - "8080:80"

  mongo:
    container_name: mongodb
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"

  mongo-seed:
    env_file:
      - .env
    build:
      context: ./db
      dockerfile: Dockerfile
      args:
        - MONGODB_URI=$DATABASE_URI
        - MONGODB_HOST=$MONGO_INITDB_ROOT_HOST
        - MONGODB_USERNAME=$MONGO_INITDB_ROOT_USERNAME
        - MONGODB_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    depends_on:
      - mongo
