### Get all blogs
GET api.traefik.me/api/blogs

### Get a single blog
GET api.traefik.me/api/blogs/62737b1b-df87-4f79-a225-be5e0778df46

### Post a blog
POST api.traefik.me/api/blogs
Content-Type: application/json

{
  "title": "Demo blog",
  "content": "This blog is a demo"
}

### Patch a blog
PATCH api.traefik.me/api/blogs/62737b1b-df87-4f79-a225-be5e0778df46
Content-Type: application/json

{
  "title": "Demo blog",
  "content": "This blog is a patched demo"
}

### Delete a blog
DELETE api.traefik.me/api/blogs/62737b1b-df87-4f79-a225-be5e0778df46