### Status
GET mgmt.traefik.me/status

### Services
GET mgmt.traefik.me/services

### All containers
GET mgmt.traefik.me/containers

### Start a service
POST mgmt.traefik.me/start
Content-Type: application/json

{
  "serviceName": "web"
}

### Stop a service
POST mgmt.traefik.me/stop
Content-Type: application/json

{
  "serviceName": "api"
}

### Scale a service
POST mgmt.traefik.me/scale
Content-Type: application/json

{
  "serviceName": "api",
  "serviceScale": 5
}

### Restart the infrastructure
POST mgmt.traefik.me/restart

### Rebuid the infrastructure
POST mgmt.traefik.me/rebuild